config/routes.rb
Rails.application.routes.draw do
  root :to => 'stations#index'

  resources :stations
  resources :lines
  resources :stops
end

#notes:

#if any not required:
   #resources :contacts, :except => [:new, :show]

#nested (eg, phones belong to contacts)
  #written out: match('contacts/:contact_id/phones/new', {:via => :get, :to => 'phones#new'}), etc.. becomes
  #   resources :contacts do
  #      resources :phones
  #    end

app/models/line.rb
class Line < ActiveRecord::Base
	validates :name, :presence => true
 
	has_many :stops
	has_many :stations, through: :stops
end

app/models/station.rb
class Station < ActiveRecord::Base
	validates :name, :presence => true
 
	has_many :stops
	has_many :lines, through: :stops
end

app/models/stop.rb
class Stop < ActiveRecord::Base 
	belongs_to :station
	belongs_to :line
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lines_controller.rb
class LinesController < ApplicationController
  
  def index 
    @lines = Line.all  #No need to specify render
  end

  def new 
    @line = Line.new #No need to specify render
  end

  def create
    @line = Line.new(line_params)  #line_params replaces params[:line], referencing method below
    if @line.save
      flash[:notice] = "Line created."
      redirect_to lines_path #replacing what would have been redirect_to (/lines)
    else
      render 'new' #replacing render('lines/new.html.erb')
    end
  end

  def show
    @line = Line.find(params[:id]) 
    render('lines/show.html.erb')
  end

  def edit 
    @line = Line.find(params[:id])
  end

  def update 
    @line = Line.find(params[:id])
    if @line.update(line_params)
     flash[:notice] = "Line updated."
      redirect_to line_path(@line)
    else
      render 'edit'
    end
  end

 def destroy 
    @line = Line.find(params[:id])
    @line.destroy
     flash[:notice] = "line Deleted"
    redirect_to lines_path
 end

 private

    def line_params
      params.require(:line).permit(:name, station_ids: [])
    end
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  
  def index
    @stations = Station.all  #No need to specify render
  end

  def new 
    @station = Station.new #No need to specify render
  end

  def create
    @station = Station.new(station_params)  #station_params replaces params[:station], referencing method below
    if @station.save
      flash[:notice] = "Station created."
      redirect_to stations_path #replacing what would have been redirect_to (/stations)
    else
      render 'new' #replacing render('stations/new.html.erb')
    end
  end

  def show
    @station = Station.find(params[:id]) 
  end

  def edit 
    @station = Station.find(params[:id])
  end

  def update 
    @station = station.find(params[:id])
    if @station.update(params[:station])
      flash[:notice] = "Station updated."
      redirect_to station_path(@station)
    else
      render 'edit'
    end
  end

 def destroy 
    @station = station.find(params[:id])
    @station.destroy
     flash[:notice] = "station Deleted"
    redirect_to stations_path
 end

 private

    def station_params
      params.require(:station).permit(:name)
    end
end

app/controllers/stops_controller.rb
class StopsController < ApplicationController
  
  def index  
    @stops = Stop.all  #No need to specify render
  end

  def new 
    @stop = Stop.new #No need to specify render
  end

  def create
    @stop = Stop.new(stop_params)  #stop_params replaces params[:stop], referencing method below
    if @stop.save
      flash[:notice] = "stop created."
      redirect_to stops_path #replacing what would have been redirect_to (/stops)
    else
      render 'new' #replacing render('stops/new.html.erb')
    end
  end

  def show
    @stop = Stop.find(params[:id]) 
    @station = Station.where(:id => @stop.station_id).first
    @line = Line.where(:id => @stop.line_id).first
    render('stops/show.html.erb')
  end

  def edit 
    @stop = Stop.find(params[:id])
  end

  def update 
    @stop = Stop.find(params[:id])
    if @stop.update(stop_params)
      flash[:notice] = "Stop updated."
      redirect_to stop_path(@stop)
    else
      render 'edit'
    end
  end

 def destroy 
    @stop = Stop.find(params[:id])
    @stop.destroy
     flash[:notice] = "stop Deleted"
    redirect_to stops_path
 end

 private

    def stop_params
      params.require(:stop).permit(:station_id, :line_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
    <h3>Please fix these errors:</h3>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

 <div class="container">
    <% if flash[:notice] %>
      <div class="alert alert-info">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-danger">
        <%= flash[:alert] %>
      </div>
    <% end %>

    <%= yield %>

 </div>
</body>
</html>

app/views/lines/_form.html.erb
<%= render("layouts/errors", :object => @line) %>

<%= form_for(@line) do |f| %>
  <div class="form-group">
    <%= f.label :name %> 
    <%= f.text_field :name %>
  </div>
  <div class="form-group">
    <%= f.collection_check_boxes :station_ids, Station.all, :id, :name %>
  </div>
  
  <%= f.submit(:class => "btn btn-primary") %>
<% end %>

app/views/lines/edit.html.erb
<%= content_for(:title, "Edit Line | Travel Tracker") %>

<h1>Edit Line</h1>

<%= render 'form' %>

</br>
</br>
<%= link_to "Return to All Lines", lines_path, :class => "btn btn-default" %>

</br>
<%= link_to "Return to Home Page", stations_path, :class => "btn btn-default" %></br>
</br>

app/views/lines/index.html.erb
<%= content_for(:title, "Lines") %>

<h1>Lines</h1>

<ul>
  <% @lines.each do |line| %>
    <li><%= link_to line.name, line_path(line) %></li>
  <% end %>
</ul>

<%= link_to "New Line", new_line_path, :class => "btn btn-default" %>

</br>
</br>
<%= link_to "Return to Home Page", stations_path, :class => "btn btn-default" %></br>
</br>

app/views/lines/new.html.erb
<%= content_for(:title, "New Line | Travel Tracker") %>

<h1>New Line</h1>

<%= render 'form' %>

</br>
</br>
<%= link_to "Return to Home Page", stations_path, :class => "btn btn-default" %></br>
</br>

app/views/lines/show.html.erb
<%= content_for(:title, "#{@line.name} | Travel Tracker") %>

<h1><%= @line.name %></h1>

<h3> Current Stations on this Line </h3>

<% @line.stations.each do |station| %>
         <p>&nbsp&nbsp&nbsp<%= link_to station.name, station_path(station) %></p>
 <% end %> 


</br>
</br>


<p><%= link_to "Edit", edit_line_path(@line), :class => "btn btn-default" %></p>
<p><%= link_to "Delete", line_path(@line), :data => {
                         :confirm => "You sure?",
                         :method => "delete"},
                         :class => "btn btn-danger" %></p>                
<p><%= link_to "Return to the line listing", lines_path %></p>

</br>
</br>
<%= link_to "Return to Home Page", stations_path, :class => "btn btn-default" %></br>
</br>

app/views/stations/_form.html.erb
<%= render("layouts/errors", :object => @station) %>

<%= form_for(@station) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  
  <%= f.submit(:class => "btn btn-primary") %>
<% end %>

app/views/stations/edit.html.erb
<%= content_for(:title, "Edit Station | Travel Tracker") %>

<h1>Edit Station</h1>

<%= render 'form' %>
</br>
</br>
<%= link_to "Return to Home Page", stations_path, :class => "btn btn-default" %></br>
</br>

app/views/stations/index.html.erb
<%= content_for(:title, "Travel Tracker") %>

<h1>Travel Tracker</h1>
</br>
<ul>
  <% @stations.each do |station| %>
    <h4>Station: <%= link_to station.name, station_path(station) %></h4>
    <p> Lines that Run Through This Station </p>
     <% station.lines.each do |line| %>
         <p>&nbsp&nbsp&nbsp<%= link_to line.name, line_path(line) %></p>
     <% end %> </br>
  <% end %>
</ul>
<%= link_to "See All Lines", lines_path, :class => "btn btn-default" %>
<%= link_to "See All Stops", stops_path, :class => "btn btn-default" %></br>
</br>
<%= link_to "Add New Station", new_station_path, :class => "btn btn-default" %></br></br>
<%= link_to "Add New Line", new_line_path, :class => "btn btn-default" %></br></br>
<%= link_to "Add New Stop (Combine a Line and a Station)", new_stop_path, :class => "btn btn-default" %>

app/views/stations/new.html.erb
<%= content_for(:title, "New Station | Travel Tracker") %>

<h1>New Station</h1>

<%= render 'form' %>

</br>
</br>
<%= link_to "Return to Home Page", stations_path, :class => "btn btn-default" %></br>
</br>

app/views/stations/show.html.erb
<%= content_for(:title, "#{@station.name} | Travel Tracker") %>

<h1><%= @station.name %></h1>

<h3> The following lines stop here: </h3>

<% @station.lines.each do |line| %>
         <h4>&nbsp&nbsp&nbsp<%= link_to line.name, line_path(line) %></h4>
 <% end %> 


</br>
</br>


<p><%= link_to "Edit", edit_line_path(@station), :class => "btn btn-default" %></p>
<p><%= link_to "Delete", line_path(@station), :data => {
                         :confirm => "You sure?",
                         :method => "delete"},
                         :class => "btn btn-danger" %></p>                
<p><%= link_to "Return to the station listing", stations_path %></p>

</br>
</br>
<%= link_to "Return to Home Page", stations_path, :class => "btn btn-default" %></br>
</br>

app/views/stops/_form.html.erb
<%= render("layouts/errors", :object => @stop) %>

<%= form_for (@stop) do |f| %>
  <div class="form-group">
    <%= f.label :station_id %>
    <%= f.collection_select :station_id, Station.all, :id, :name %>
  </div>
  <div class="form-group">
    <%= f.label :line_id %>
    <%= f.collection_select :line_id, Line.all, :id, :name %>
  </div>
  <%= f.submit(:class=>"btn btn-primary")%>
<% end %>

app/views/stops/edit.html.erb
<%= content_for(:title, "Edit Stop | Travel Tracker") %>

<h1>Edit Stop</h1>

<%= render 'form' %>
</br>
</br>
<%= link_to "Return to All Stops", stops_path, :class => "btn btn-default" %></br>
</br>

</br>
<%= link_to "Return to Home Page", stations_path, :class => "btn btn-default" %></br>
</br>

app/views/stops/index.html.erb
<%= content_for(:title, "Stops | Travel Tracker") %>

<h1>Stops</h1>

<ul>
  <% @stops.each do |stop| %>
    <li><%= link_to "Line / Station: #{stop.line.name} stopping at #{stop.station.name}", stop_path(stop) %></li>
  <% end %>
</ul>

<%= link_to "New Stop", new_stop_path, :class => "btn btn-default" %>

</br>
<%= link_to "Return to Home Page", stations_path, :class => "btn btn-default" %></br>
</br>

app/views/stops/new.html.erb
<%= content_for(:title, "New Stop | Travel Tracker") %>

<h1>New Stop</h1>

<%= render 'form' %>

</br>
</br>
<%= link_to "Return to Home Page", stations_path, :class => "btn btn-default" %></br>
</br>

app/views/stops/show.html.erb
<%= content_for(:title, "#{@stop.name} | Travel Tracker") %>

<h1><%= @stop.name %></h1>

<h3><%= "Line: #{@line.name}" %></h3>

<h3><%= "Stop: #{@station.name}" %></h3>

</br>
</br>
</br>



<p><%= link_to "Edit", edit_stop_path(@stop), :class => "btn btn-default" %></p>
<p><%= link_to "Delete", stop_path(@stop), :data => {
                         :confirm => "You sure?",
                         :method => "delete"},
                         :class => "btn btn-danger" %></p>                
<p><%= link_to "Return to the stop listing", stops_path %></p>

</br>
<%= link_to "Return to Home Page", stations_path, :class => "btn btn-default" %></br>
</br>